App logic
Areukiddin/Test-Guru pull request #7
Opened 2021-06-21 11:14 UTC by Areukiddin

2021-06-21 13:34 UTC, VidgarVii requested changes

2021-06-21 13:34 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
для одного экшена колбек не объявляют. Ухудшается читаемость

2021-06-21 13:34 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user.tests.delete(@test) if @user.tests.include?(@test)
не надо удалять статистику пройденных тестов 
юзер может проходить тест сколько угодно раз

2021-06-21 13:34 UTC, VidgarVii commented on app/helpers/results_helper.rb
> +  end
вот эта вся бизнес логика в данный момент должна находиться в модели. Хелперы нужны только за упрощение верстки.
Пусть объект test_passage и отвечает за прохождение теста

2021-06-21 13:34 UTC, VidgarVii commented on app/models/result.rb
> +  end
в описании ДЗ представлен лаконичный и читаемый код для этого метода. Разберись как он работает и протестируй

2021-06-21 13:46 UTC, Areukiddin commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
<img width="1552" alt="Снимок экрана 2021-06-21 в 16 46 10" src="https://user-images.githubusercontent.com/28897287/122772570-31696580-d2b0-11eb-8069-983a36ed48ca.png">

2021-06-22 13:41 UTC, VidgarVii requested changes

2021-06-22 13:41 UTC, VidgarVii commented on app/models/result.rb
> +    correct_answers_percent.to_i >= 85
лучше "магические цифры" хранить в константах с "говорящими именами"
например `SUCCESS_RATIO`

2021-06-22 13:41 UTC, VidgarVii commented on app/models/result.rb
> +    test_correct_answers.ids.sort == answer_ids.map(&:to_i).sort
здесь хорошо бы учесть ситуацию когда в `answer_ids` прийдет `nil`
код при этом не должен падать

2021-06-24 12:15 UTC, merged